# Generated by Django 6.0.7 on 2026-08-08 01:05

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='The day the event starts.', verbose_name='Date')),
                ('end_date', models.DateField(blank=True, help_text='Only for events running more than one day, e.g. an Akhand Paath.', null=True, verbose_name='Last day')),
                ('start_time', models.TimeField(blank=True, help_text='Optional. Leave blank if it varies.', null=True)),
                ('location', models.CharField(blank=True, default='Main Hall', help_text='Optional.', max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Optional. A poster or photo for this event.', upload_to='events/', verbose_name='Poster')),
                ('description', models.TextField(blank=True, help_text='A short paragraph shown under the event title.')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlighted events stand out and are listed first.', verbose_name='Highlight this event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events & posters',
                'ordering': ['date', 'start_time'],
            },
            bases=(content.models.ImageProcessingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Large, landscape photos look best. Big files are fine — they are shrunk automatically.', upload_to='photos/')),
                ('category', models.CharField(choices=[('hero', 'Home page slideshow'), ('history', 'History (About section)'), ('academy', 'Khalsa Academy gallery')], default='hero', max_length=20, verbose_name='Where it appears')),
                ('caption', models.CharField(blank=True, help_text='Optional. Leave blank for the home page slideshow — that one shows no text. Also used by screen readers.', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Change the numbers to reorder.', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide the photo without deleting it.', verbose_name='Show on the website')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos on the website',
                'ordering': ['sort_order', 'id'],
            },
            bases=(content.models.ImageProcessingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="For example 'Morning Program' or 'Wednesday & Friday'.", max_length=120)),
                ('days', models.CharField(blank=True, help_text="For example 'Daily' or '7 days a week'. Optional.", max_length=120)),
                ('items', models.TextField(help_text='For example: Nitnem · Asa Di Vaar · Ardas · Hukamnama', verbose_name='What happens')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Use for programmes that only run on certain days.', verbose_name='Highlight this row')),
            ],
            options={
                'verbose_name': 'Programme row',
                'verbose_name_plural': 'Daily programme',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sikh Center of SF Bay Area', help_text='Shown in the top bar, the footer, and browser tabs.', max_length=120, verbose_name='Gurdwara name')),
                ('gurmukhi_name', models.CharField(blank=True, default='ਸਿੱਖ ਸੈਂਟਰ', help_text='Shown in smaller text under the name. Leave blank to hide it.', max_length=120, verbose_name='Name in Gurmukhi')),
                ('location_line', models.CharField(blank=True, default='Gurdwara Sahib El Sobrante', help_text="Shown under the gurdwara name, e.g. 'Gurdwara Sahib El Sobrante'.", max_length=120, verbose_name='Location line')),
                ('address_line1', models.CharField(default='3550 Hillcrest Rd', max_length=120)),
                ('address_line2', models.CharField(default='El Sobrante, CA 94803', max_length=120)),
                ('phone_main', models.CharField(default='(510) 223-9987', max_length=40, verbose_name='Main phone')),
                ('phone_alt', models.CharField(blank=True, default='(510) 223-1102', help_text='Leave blank if there is only one number.', max_length=40, verbose_name='Second phone')),
                ('email', models.EmailField(blank=True, default='info@thesikhcenter.com', max_length=254)),
                ('opening_hours', models.CharField(blank=True, default='Open daily 5:00 AM – 8:30 PM', help_text='Shown on the Home and Contact pages.', max_length=120)),
                ('youtube_channel_id', models.CharField(blank=True, default='UCx1y5VenBaV9WspiK_oAnxQ', help_text='The livestream page always plays whatever is live on this channel, so it never needs changing when a new stream starts. Find it in YouTube Studio under Settings → Channel → Advanced settings.', max_length=64, verbose_name='YouTube channel ID')),
                ('youtube_channel_url', models.URLField(blank=True, default='https://www.youtube.com/c/ElSobranteGurdwaraSahib', help_text="Used for the 'Open on YouTube' links.", verbose_name='YouTube channel link')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/sfsikhcenter', verbose_name='Facebook page link')),
                ('google_calendar_id', models.CharField(blank=True, help_text="The gurdwara's own calendar, where paths and bookings are entered. In Google Calendar: Settings → click the calendar → 'Integrate calendar' → copy 'Calendar ID'. Leave blank to hide the calendar.", max_length=200, verbose_name='Google Calendar ID')),
                ('nanakshahi_calendar_id', models.CharField(blank=True, default='8lh6gp8c7pdm7ta30435i2k854@group.calendar.google.com', help_text='Adds Gurpurab and Nanakshahi dates on top of the gurdwara calendar. This updates itself every year — no action needed.', max_length=200, verbose_name='Nanakshahi calendar ID')),
                ('booking_note', models.CharField(blank=True, default='To book a path, please call the Gurdwara.', help_text='Shown above the calendar. Bookings are not taken on the website.', max_length=200)),
            ],
            options={
                'verbose_name': 'Gurdwara details',
                'verbose_name_plural': 'Gurdwara details',
            },
        ),
    ]
