# Generated by Django 6.0.7 on 2026-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.CharField(blank=True, help_text='Only needed for photos taken by someone outside the gurdwara. Shown in small text in the footer.', max_length=200, verbose_name='Photo credit'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, help_text='A short description of the photo. Always read out by screen readers. Shown on the page for History and Academy photos; the home page slideshow deliberately shows no text.', max_length=200),
        ),
    ]
