# Generated by Django 6.0.7 on 2026-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_photo_image_height_photo_image_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home_about', 'Home — About the Gurdwara'), ('home_visit', 'Home — Visit us'), ('schedule_header', 'Schedule — page heading'), ('events_header', 'Events — page heading'), ('events_calendar', 'Events — calendar section'), ('livestream_header', 'Livestream — page heading'), ('livestream_program', 'Livestream — daily program box'), ('contact_header', 'Contact — page heading'), ('contact_parking', 'Contact — parking & access'), ('contact_expect', 'Contact — what to expect')], max_length=40, unique=True)),
                ('heading', models.CharField(blank=True, help_text='The bold line above the text.', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Leave a blank line between paragraphs. For the two Contact lists, put each point on its own line.', verbose_name='Text')),
                ('sort_order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Page text',
                'verbose_name_plural': 'Text on the pages',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="The big text, e.g. '1969' or '5 acres'.", max_length=40)),
                ('label', models.CharField(help_text="The small text underneath, e.g. 'Year established'.", max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.', verbose_name='Show on the website')),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts on the home page',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, help_text='A short description of the photo. Always read out by screen readers. Shown under History photos; the home page slideshow deliberately shows no text.', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('hero', 'Home page slideshow'), ('history', 'History (About section)')], default='hero', max_length=20, verbose_name='Where it appears'),
        ),
    ]
